#!/bin/bash

source ~/.bashrc

# Where's my Python
source /datascope/slurm/miniconda3/bin/activate viska-tf28
export PYTHONPATH=.:../pysynphot:../SciScript-Python/py3

# Where's my PFS 
export ROOT=/home/swei20/PhysicsInformedML
export DATA=/home/swei20/PhysicsInformedML/data

# Work around issues with saving weights when running on multiple threads
export HDF5_USE_FILE_LOCKING=FALSE

# Disable tensorflow deprecation warnings
export TF_CPP_MIN_LOG_LEVEL=2

# Enable more cores for numexpr
export NUMEXPR_MAX_THREADS=32

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib



cd $ROOT

echo "2024! 2024! "
# echo "Data directory is $PhysicsInformedML_DATA"